[[rename_node]]
match = "剩余流量：(.*$)"
replace = "D:$1"

[[rename_node]]
match = "过期时间：.*([0-9]{2})-(.*)-(.*)"
replace = "T:$1/$2/$3"

[[rename_node]]
match = "专线(?![A-Z])"
replace = "PC"

[[rename_node]]
match = "中继(?![A-Z])|中转|隧道"
replace = "RE"

[[rename_node]]
match = "冷门-"
replace = ""

[[rename_node]]
match = "澳大利亚"
replace = "AU"

[[rename_node]]
match = "悉尼"
replace = "AU"

[[rename_node]]
match = "加拿大"
replace = "CA"

[[rename_node]]
match = "巴西"
replace = "BO"

[[rename_node]]
match = "德国"
replace = "DE"

[[rename_node]]
match = "香港"
replace = "HK"

[[rename_node]]
match = "印度"
replace = "IN"

[[rename_node]]
match = "日本"
replace = "JP"

[[rename_node]]
match = "韩国"
replace = "KR"

[[rename_node]]
match = "俄罗斯"
replace = "RU"

[[rename_node]]
match = "新加坡"
replace = "SG"

[[rename_node]]
match = "西班牙"
replace = "ES"

[[rename_node]]
match = "菲律宾"
replace = "PH"

[[rename_node]]
match = "泰国"
replace = "TH"

[[rename_node]]
match = "荷兰"
replace = "NL"

[[rename_node]]
match = "台湾"
replace = "TW"

[[rename_node]]
match = "英国"
replace = "UK"

[[rename_node]]
match = "美国"
replace = "US"

[[rename_node]]
match = "瑞士"
replace = "CH"

[[rename_node]]
match = "马来西亚"
replace = "MY"

[[rename_node]]
match = "土耳其"
replace = "TU"

[[rename_node]]
match = "阿根廷"
replace = "AR"

[[rename_node]]
match = "波兰"
replace = "PL"

[[rename_node]]
match = "印尼"
replace = "ID"

[[rename_node]]
match = "越南"
replace = "VN"

[[rename_node]]
match = "墨西哥"
replace = "MX"

[[rename_node]]
match = "意大利"
replace = "IT"

[[rename_node]]
match = "法国"
replace = "FR"

[[rename_node]]
match = "匈牙利"
replace = "HU"

[[rename_node]]
match = "瑞典"
replace = "SE"

[[rename_node]]
match = "卢森堡"
replace = "LU"

[[rename_node]]
match = "乌克兰"
replace = "UA"

[[rename_node]]
match = "奥地利"
replace = "AT"

[[rename_node]]
match = "保加利亚"
replace = "BG"

[[rename_node]]
match = "拉脱维亚"
replace = "LV"

[[rename_node]]
match = "北京"
replace = "BJ"

[[rename_node]]
match = "常州"
replace = "CZ"

[[rename_node]]
match = "广东"
replace = "GD"

[[rename_node]]
match = "杭州"
replace = "HZ"

[[rename_node]]
match = "江苏"
replace = "JS"

[[rename_node]]
match = "山东"
replace = "SD"

[[rename_node]]
match = "上海"
replace = "SH"

[[rename_node]]
match = "绍兴"
replace = "SX"

[[rename_node]]
match = "深圳"
replace = "SZ"

[[rename_node]]
match = "浙江"
replace = "ZJ"

[[rename_node]]
match = "三鲜"
replace = "SX"

[[rename_node]]
match = "广州"
replace = "GZ"

[[rename_node]]
match = "Azure"
replace = "AZ"

[[rename_node]]
match = "电信"
replace = "CT"

[[rename_node]]
match = "联通"
replace = "CU"

[[rename_node]]
match = "移动"
replace = "CM"

[[rename_node]]
match = "丨流媒体"
replace = "|◈"

[[rename_node]]
match = "(.*[0-9]{1,})([A-Z]{2})([A-Z{1}])(.*)丨(.*)"
replace = "RE|$2|$4|$5|$1"

[[rename_node]]
match = "(防失联).*([0-9]{2})(倍率).*"
replace = "EX|$2x|V1"

[[rename_node]]
match = "(.*)([A-Z]{2})公益.*"
replace = "RE|$2|00|1x|V0"

[[rename_node]]
match = "(.*[0-9]{1,})([A-Z]{2}).*丨(.*)"
replace = "RE|$2|$3|$1"